-- CREATE LIBRARY DATABASE IF NOT EXISTS
DROP DATABASE IF EXISTS tryer;
CREATE DATABASE IF NOT EXISTS tryer;

USE tryer;

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
);


